server:
  port: 8083

spring:
  application:
    name: content-service
  datasource:
    url: jdbc:postgresql://content-db:5432/content_db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
